# Generated by Django 4.2 on 2023-05-21 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=2000)),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tip_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Tip',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('size', models.PositiveIntegerField()),
                ('rooms', models.CharField(max_length=4)),
                ('balcony', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='property_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Property',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='nadlan_app/static/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='nadlan_app.property')),
            ],
            options={
                'db_table': 'Photo',
            },
        ),
    ]
