# Generated by Django 4.2 on 2023-06-28 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nadlan_app', '0002_rename_content_contact_message_remove_contact_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='real_estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
