# Generated by Django 4.2 on 2023-06-28 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nadlan_app', '0003_alter_property_real_estate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='real_estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tip_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
